### ISSUE TITLE
Don't stop appending if a single append is missing

### ISSUE THREAD

**Issue by SaschaMann** [exercism/org-wide-files#13]
This line is why the append wasn't respected in Elixir, but was respected in the Julia repo: https://github.com/exercism/org-wide-files/blob/784d161f18fcee93c93bb28e723f2444a4f9ef4a/.github/workflows/sync-tracks.yml#L165

The `exit(0)` needs to be a `continue`.

(Writing this down now because I'm paying attention to the call atm, will fix later)

**Comment by ErikSchierboom** [comment]
Great catch! Thanks
