### ISSUE TITLE
Move repository_dispatch trigger to separate workflow

### ISSUE THREAD

**Issue by SaschaMann** [exercism/org-wide-files#164]
These events are triggered by changes in the downstream repos. The people (indirectly) triggering them typically don't have access to this repo, so even if they wanted to, they couldn't cancel the 5 min abort timer. So I think we could reduce friction in dealing with appends by moving this event to its own workflow and skipping the timer in it.

**Comment by ErikSchierboom** [comment]
Yeah, probably a good idea

**Comment by fhayyuu** [comment]
YES

**Comment by SaschaMann** [comment]
@fhayyuu Does that mean you want to work on this?

**Comment by Santiago00lp** [comment]
Hi, I'm new to Exercim and I want to help with this issue.

**Comment by ErikSchierboom** [comment]
I don't think we really need this feature anymore to be honest. It has never really been an issue. Therefore, I'm closing this issue. Thanks for wanting to help.
