### ISSUE TITLE
consider adding `fetch-configlet`

### ISSUE THREAD

**Issue by ee7** [exercism/org-wide-files#262]
Follow-up from https://github.com/exercism/elixir/pull/1218#issuecomment-1285847533 and https://github.com/exercism/elixir/pull/1217#issuecomment-1285855493

Let's try to:

- Ensure that `CODEOWNERS` specifies the correct filename in every track repo - some repos had different filenames for `fetch-configlet` in the past.
- Ideally, make the `fetch-configlet`-updating process also target https://github.com/exercism/request-new-language-track/

**Comment by kytrinyx** [comment]
> The fetch-configlet scripts are clearly files that we want in many repos, with a single source of truth.

It just occurred to me that we don't actually want them in _all_ the repositories. Just the track repositories.

How about having Configlet do it? Configlet is also only in the track repositories.

**Comment by kytrinyx** [comment]
I would prefer the `fetch-configlet` scripts to live in the `configlet` repository.
But I would also prefer `org-wide-files` to do the syncing, especially since it can support `tracks-files`.

I think my preference would be to see if we can make `org-wide-files` get the file from the configlet repository without that turning into a mess.

**Comment by kytrinyx** [comment]
It would make sense to target it. That way newly bootstrapped repositories would be fully up-to-date.

**Comment by ErikSchierboom** [comment]
Yeah that makes sense. Could you create an issue?

**Comment by ErikSchierboom** [comment]
> If it's not easy, what do we think about just duplicating the scripts for now? That is: keep fetch-configlet scripts in the configlet repo, add them to org-wide-files too, and update them in org-wide-files when we want to distribute the changes?

I'm fine with duplicating them.

> Also, should we add the PowerShell script to org-wide-files? I lean towards "no", but we do need to update it on every track that it exists (for the same upcoming asset renaming). I'm not a PowerShell user, so I don't want to commit to maintaining it, and it will need more updates in the future (see [open issues for fetch-configlet](https://github.com/exercism/configlet/issues?q=is%3Aissue+fetch-configlet+is%3Aopen)).

Well, I think it would make sense to have them sync too, but only for the tracks interested in them. We could maybe use the `org-wide-files-config.toml` file that we also used to enable or disable format checking (see https://github.com/exercism/julia/blob/main/.github/org-wide-files-config.toml).

**Comment by kytrinyx** [comment]
I believe the ps1 script is in all tracks at the moment (I made the incorrect assumption that this was the desired behavior, so I added them in the last batch sync PRs).

This script would be used by any contributor/maintainer who is developing on a Windows machine, right?

**Comment by ErikSchierboom** [comment]
> org-wide-files can do that, right?

Not yet no. And I don't know Julia: https://github.com/exercism/org-wide-files/blob/main/scripts/apply-track-config.jl 😱

**Comment by kytrinyx** [comment]
Is there a mechanism for tracks to configure which (optional) files they want? If so I think it's fine to make the `.ps1` file optional and only sync it if the track adds it to the configuration.

**Comment by ErikSchierboom** [comment]
> Is there a mechanism for tracks to configure which (optional) files they want? If so I think it's fine to make the .ps1 file optional and only sync it if the track adds it to the configuration.

There isn't, we'd have to build it ourselves.

**Comment by kytrinyx** [comment]
I think my suggestion right now is to get the basic `fetch-configlet` script included now, and leave the `.ps1` script off. Let's just leave people to get ps1 updated if they care about it (for now).

**Comment by ErikSchierboom** [comment]
Sounds like a plan
