### ISSUE TITLE
exercism-bot: consider creating branches without the :robot: emoji

### ISSUE THREAD

**Issue by ee7** [exercism/org-wide-files#309]
GitHub now [shows a warning](https://github.com/exercism/nim/pull/528) when viewing a PR with :robot: in the branch name:

> The head ref may contain hidden characters: `"\u{1F916}/org-wide-files/5829783659"`

**Comment by sanderploegsma** [comment]
Fixed by @ErikSchierboom in https://github.com/exercism/org-wide-files/pull/326, can be closed.
